var num=-178976;
var absolute_num=Math.abs(num);
console.log(absolute_num);
var h=5.865346;
var result=Math.floor(h);
console.log(result);
var r=Math.random()*100;
console.log(r);
var shafin=Math.round(r);
console.log(shafin);